create extension if not exists "vector" with schema "extensions";

drop extension if exists "pg_net";


  create table "public"."conversations" (
    "id" bigint generated always as identity not null,
    "user_id" uuid not null,
    "title" text,
    "created_at" timestamp with time zone default now(),
    "summary" text,
    "last_summarized_message_id" bigint
      );


alter table "public"."conversations" enable row level security;


  create table "public"."document_chunks" (
    "id" bigint generated always as identity not null,
    "document_id" bigint not null,
    "chunk_index" integer not null,
    "content" text not null,
    "embedding" extensions.vector(768),
    "created_at" timestamp with time zone default now()
      );


alter table "public"."document_chunks" enable row level security;


  create table "public"."documents" (
    "id" bigint generated always as identity not null,
    "filename" text not null,
    "file_type" text not null,
    "created_at" timestamp with time zone default now(),
    "access_level" text not null default 'employee'::text
      );


alter table "public"."documents" enable row level security;


  create table "public"."messages" (
    "id" bigint generated always as identity not null,
    "conversation_id" bigint not null,
    "role" text not null,
    "content" text not null,
    "created_at" timestamp with time zone default now()
      );


alter table "public"."messages" enable row level security;


  create table "public"."request_logs" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid,
    "conversation_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "route" text,
    "retrieval_query" text,
    "retrieved_documents" jsonb,
    "retrieved_chunks" jsonb,
    "model" text,
    "routing_latency_ms" integer,
    "retrieval_latency_ms" integer,
    "generation_latency_ms" integer,
    "total_latency_ms" integer,
    "input_tokens" integer,
    "output_tokens" integer,
    "estimated_cost_usd" numeric(12,8),
    "retry_count" integer not null default 0,
    "errors_handled" jsonb not null default '[]'::jsonb,
    "final_status" text not null default 'success'::text,
    "final_error" text,
    "provider" text,
    "total_tokens" integer,
    "retrieval_count" integer
      );


alter table "public"."request_logs" enable row level security;


  create table "public"."users" (
    "id" uuid not null,
    "name" text,
    "created_at" timestamp with time zone default now(),
    "role" text not null default 'employee'::text,
    "email" text
      );


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX conversations_pkey ON public.conversations USING btree (id);

CREATE UNIQUE INDEX document_chunks_pkey ON public.document_chunks USING btree (id);

CREATE UNIQUE INDEX documents_pkey ON public.documents USING btree (id);

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

CREATE UNIQUE INDEX request_logs_pkey ON public.request_logs USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."conversations" add constraint "conversations_pkey" PRIMARY KEY using index "conversations_pkey";

alter table "public"."document_chunks" add constraint "document_chunks_pkey" PRIMARY KEY using index "document_chunks_pkey";

alter table "public"."documents" add constraint "documents_pkey" PRIMARY KEY using index "documents_pkey";

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."request_logs" add constraint "request_logs_pkey" PRIMARY KEY using index "request_logs_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."conversations" add constraint "conversations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE not valid;

alter table "public"."conversations" validate constraint "conversations_user_id_fkey";

alter table "public"."document_chunks" add constraint "document_chunks_document_id_fkey" FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE not valid;

alter table "public"."document_chunks" validate constraint "document_chunks_document_id_fkey";

alter table "public"."documents" add constraint "documents_access_level_check" CHECK ((access_level = ANY (ARRAY['employee'::text, 'manager'::text, 'hr'::text, 'admin'::text]))) not valid;

alter table "public"."documents" validate constraint "documents_access_level_check";

alter table "public"."messages" add constraint "messages_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE CASCADE not valid;

alter table "public"."messages" validate constraint "messages_conversation_id_fkey";

alter table "public"."messages" add constraint "messages_role_check" CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text]))) not valid;

alter table "public"."messages" validate constraint "messages_role_check";

alter table "public"."request_logs" add constraint "request_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL not valid;

alter table "public"."request_logs" validate constraint "request_logs_user_id_fkey";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_id_fkey";

alter table "public"."users" add constraint "users_role_check" CHECK ((role = ANY (ARRAY['employee'::text, 'manager'::text, 'hr'::text, 'admin'::text]))) not valid;

alter table "public"."users" validate constraint "users_role_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
    INSERT INTO public.users (id, name)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data ->> 'name', NEW.email)
    );

    RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.match_document_chunks(query_embedding extensions.vector, match_count integer DEFAULT 5)
 RETURNS TABLE(id bigint, document_id bigint, chunk_index integer, content text, filename text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT
        dc.id,
        dc.document_id,
        dc.chunk_index,
        dc.content,
        d.filename,
        1 - (dc.embedding <=> query_embedding) AS similarity
    FROM public.document_chunks dc
    JOIN public.documents d
        ON d.id = dc.document_id
    WHERE dc.embedding IS NOT NULL
    ORDER BY dc.embedding <=> query_embedding
    LIMIT match_count;
$function$
;

CREATE OR REPLACE FUNCTION public.match_document_chunks(query_embedding extensions.vector, user_role text, match_count integer DEFAULT 5)
 RETURNS TABLE(id bigint, document_id bigint, chunk_index integer, content text, filename text, similarity double precision)
 LANGUAGE sql
 STABLE
AS $function$
    SELECT
        dc.id,
        dc.document_id,
        dc.chunk_index,
        dc.content,
        d.filename,
        1 - (dc.embedding <=> query_embedding) AS similarity
    FROM public.document_chunks dc
    JOIN public.documents d
        ON d.id = dc.document_id
    WHERE dc.embedding IS NOT NULL
      AND (
          d.access_level = 'employee'
          OR (d.access_level = 'manager' AND user_role IN ('manager', 'admin'))
          OR (d.access_level = 'hr' AND user_role IN ('hr', 'admin'))
          OR (d.access_level = 'admin' AND user_role = 'admin')
      )
    ORDER BY dc.embedding <=> query_embedding
    LIMIT match_count;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

grant references on table "public"."conversations" to "anon";

grant trigger on table "public"."conversations" to "anon";

grant truncate on table "public"."conversations" to "anon";

grant insert on table "public"."conversations" to "authenticated";

grant references on table "public"."conversations" to "authenticated";

grant select on table "public"."conversations" to "authenticated";

grant trigger on table "public"."conversations" to "authenticated";

grant truncate on table "public"."conversations" to "authenticated";

grant update on table "public"."conversations" to "authenticated";

grant references on table "public"."conversations" to "service_role";

grant trigger on table "public"."conversations" to "service_role";

grant truncate on table "public"."conversations" to "service_role";

grant references on table "public"."document_chunks" to "anon";

grant trigger on table "public"."document_chunks" to "anon";

grant truncate on table "public"."document_chunks" to "anon";

grant references on table "public"."document_chunks" to "authenticated";

grant trigger on table "public"."document_chunks" to "authenticated";

grant truncate on table "public"."document_chunks" to "authenticated";

grant delete on table "public"."document_chunks" to "service_role";

grant insert on table "public"."document_chunks" to "service_role";

grant references on table "public"."document_chunks" to "service_role";

grant select on table "public"."document_chunks" to "service_role";

grant trigger on table "public"."document_chunks" to "service_role";

grant truncate on table "public"."document_chunks" to "service_role";

grant update on table "public"."document_chunks" to "service_role";

grant references on table "public"."documents" to "anon";

grant trigger on table "public"."documents" to "anon";

grant truncate on table "public"."documents" to "anon";

grant references on table "public"."documents" to "authenticated";

grant trigger on table "public"."documents" to "authenticated";

grant truncate on table "public"."documents" to "authenticated";

grant delete on table "public"."documents" to "service_role";

grant insert on table "public"."documents" to "service_role";

grant references on table "public"."documents" to "service_role";

grant select on table "public"."documents" to "service_role";

grant trigger on table "public"."documents" to "service_role";

grant truncate on table "public"."documents" to "service_role";

grant update on table "public"."documents" to "service_role";

grant references on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant references on table "public"."request_logs" to "anon";

grant trigger on table "public"."request_logs" to "anon";

grant truncate on table "public"."request_logs" to "anon";

grant references on table "public"."request_logs" to "authenticated";

grant trigger on table "public"."request_logs" to "authenticated";

grant truncate on table "public"."request_logs" to "authenticated";

grant insert on table "public"."request_logs" to "service_role";

grant references on table "public"."request_logs" to "service_role";

grant select on table "public"."request_logs" to "service_role";

grant trigger on table "public"."request_logs" to "service_role";

grant truncate on table "public"."request_logs" to "service_role";

grant references on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant references on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";


  create policy "users can create own conversations"
  on "public"."conversations"
  as permissive
  for insert
  to authenticated
with check ((auth.uid() = user_id));



  create policy "users can read own conversations"
  on "public"."conversations"
  as permissive
  for select
  to authenticated
using ((auth.uid() = user_id));



  create policy "users can update own conversations"
  on "public"."conversations"
  as permissive
  for update
  to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));



  create policy "users can create own messages"
  on "public"."messages"
  as permissive
  for insert
  to authenticated
with check ((EXISTS ( SELECT 1
   FROM public.conversations
  WHERE ((conversations.id = messages.conversation_id) AND (conversations.user_id = auth.uid())))));



  create policy "users can read own messages"
  on "public"."messages"
  as permissive
  for select
  to authenticated
using ((EXISTS ( SELECT 1
   FROM public.conversations
  WHERE ((conversations.id = messages.conversation_id) AND (conversations.user_id = auth.uid())))));



  create policy "users can read own profile"
  on "public"."users"
  as permissive
  for select
  to authenticated
using ((auth.uid() = id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


